### ISSUE TITLE
No errors. But, no result as well.

### ISSUE THREAD

**Issue by amlxv** [Androz2091/discord-music-bot#2]
### Terminal
![Image From Terminal](https://i.imgur.com/LWyovtB.png)

### Discord
![Image From Discord](https://i.imgur.com/XjLWAwA.png)

**Comment by tsukasaroot** [comment]
I do have the same issue, i've waited an hour cuz saw something about propagation, but no results, it's like commands aren't registered. I gave applications.command + bot scope.

**Comment by shehrozealim** [comment]
> I do have the same issue, i've waited an hour cuz saw something about propagation, but no results, it's like commands aren't registered. I gave applications.commands + bot scope.

I didnt understand what you said can you be more elaborate please. Thank You.

**Comment by tsukasaroot** [comment]
Sorry, i noticed my message is a bit of a mess.

I just wanted to give a bit more informations as I have the same issue as amlxv.
I added the scopes about applications.commands and bot in discord developper's application panel, when creating the Oauth2 link to invite bot.
So even with permissions supposedly correctly set, slash commands doesn't display on the server where the bot joined.

**Comment by shehrozealim** [comment]
I have message Androz on Discord and I am currently waiting for his reply. If there are any updates I will update the post.

**Comment by Androz2091** [comment]
The bot uses **Slash Commands**. Specify the ID of your server in the .env file and it will work. Otherwise, wait a bit because creating commands can take a few hours for Discord.

**Comment by Androz2091** [comment]
I will be available on my discord server if you want to share your screen

**Comment by amlxv** [comment]
I tried to re-clone the repos and do the same things again. And it works.

![](https://i.imgur.com/tEQoOsw.png)

However, another problem comes up, The bot doesn't play and store music in the queue.

![](https://i.imgur.com/INEdbrY.png)

**Comment by RealRunSpace** [comment]
Fix: install opusscript as well

**Comment by Noman17-tect** [comment]
> Hello, same here, the bot does not play, he even joins to the channel but no audio is played

Getting same here, tried installing opusscript but didn't worked... Please Help
