### ISSUE TITLE
Bot Commands stuck on ... is thinking?

### ISSUE THREAD

**Issue by Ethan1498** [Androz2091/discord-music-bot#20]
Slash commands work, bring the bot into the channel, but the bot produces no audio whilst in the channel and each command has ... is thinking constantly under it
<img width="97" alt="Screenshot 2021-09-14 at 14 37 35" src="https://user-images.githubusercontent.com/41568319/133267735-d158c4a2-7139-4cc4-beab-b45de77abb60.png">

**Comment by ZhunCn** [comment]
For the "is thinking?" bug, if you cloned the repository before September 8th, update to the latest commit. This was a possible issue that was fixed with #13 pull request that was recently merged. If you are using docker, you will also need to rebuild the image.
I didn't encounter the audio issue, but you may want to look at #12 or #2

**Comment by Ethan1498** [comment]
Hmmm, I cloned the repo today, so I am on the latest commit, the bot just won't run any command it seems, all them will get stuck on is thinking constantly until the message is deleted from the server, not sure if it could be an issue with me running it via Heroku?

**Comment by ZhunCn** [comment]
I do know that Heroku's free tier will cause the containers to sleep if it is inactive for more than 30 minutes, but I'm not sure if that would affect the bot's general functionality or not. Try temporarily hosting the bot on your own computer.
I'm currently running the bot with Docker on unRAID OS (unix based), and it hasn't come into any issues. It has more than 1 week uptime right now.

**Comment by Androz2091** [comment]
Yes, I think that FFMPEG can't run on Heroku. Same for node-opus, I'm not sure if it can be build or not, but I guess Heroku doesn't allow such heavy to install dependencies.

**Comment by Ethan1498** [comment]
Okay cheers guys, I will try running the bot locally this evening and seeing if that solves the issue, if it does I will spin up an AWS instance and test that!

**Comment by Ethan1498** [comment]
Okay quick update, running locally seems to have sorted this issue, so Heroku was causing the headache...

Will host on AWS instead, thank you for the help!
