### ISSUE TITLE
Queues track but not play it

### ISSUE THREAD

**Issue by KC080** [Androz2091/discord-music-bot#26]
I recently got the bot to work after upgrading NodeJS on repl.it, however, whenever I use the /play command, it says the song has been queued, but not playing.

![image](https://user-images.githubusercontent.com/77486627/133455642-abd94da2-1239-42d8-b5d3-885aa97af138.png)

**Comment by thyme4soup** [comment]
See #12 
TL;DR `yarn add opusscript` or `npm install opusscript`

**Comment by KC080** [comment]
> See #12
> TL;DR `yarn add opusscript` or `npm install opusscript`
> (at least that's what fixed it for me)

doesnt work for me. the problem is when i use the /np command it says theres nothing playing although i sent the /play command.

**Comment by gritn0** [comment]
Having the same error

**Comment by acffordyce973** [comment]
Same issue here. It did play once and now nothing.

**Comment by Ethan1498** [comment]
Is https://ffmpeg.org/download.html installed? You have to do this step manually

**Comment by acffordyce973** [comment]
Installed it via apt on Ubuntu 20.04.

**Comment by Ethan1498** [comment]
Any errors in console when bot is launched?

**Comment by Zebiano** [comment]
Make sure to:
1. Run Node v16
2. Install ffmpeg with `sudo apt install ffmpeg`
3. Install `opusscript` with `npm i opusscript` 
4. Invite your bot with a link like this one:
```
https://discord.com/api/oauth2/authorize?client_id=YOUR_BOT_ID&permissions=0&scope=applications.commands%20bot
```
This should be enough to get the bot working. Just managed to do it!

**Comment by voltrare** [comment]
I got it to work by installing ffmpeg and reinstalling everything back without opusscript
I think the main reason is because ffmpeg is missing

**Comment by henriiqueg** [comment]
For me it worked just deleting node_modules and running `yarn` again

**Comment by KC080** [comment]
found out the solution. you need FFmpeg. though I can only use the bot when I run it locally because repl.it does not support FFmpeg. Thanks for the help.

**Comment by voltrare** [comment]
> found out the solution. you need FFmpeg. though I can only use the bot when I run it locally because repl.it does not support FFmpeg. Thanks for the help.

check my fork ive added replit support
