### ISSUE TITLE
Bot cannot retrieve guild object

### ISSUE THREAD

**Issue by samusaran** [Androz2091/discord-music-bot#28]
I can't get the bot to work.

If I breakpoint on `play.js:28` I can see that the following line sets `guild` to `undefined`:
```
const guild = client.guilds.cache.get(ctx.guildID);
```

I can see `ctx.guildID` contains my guild ID.

Why can't the bot manage to read the guild?

**Comment by rhozetta** [comment]
Did you enable the intent?

**Comment by samusaran** [comment]
@rhozetta I managed to solve by adding the "bot" permission to the bot
