### ISSUE TITLE
Bot not loading

### ISSUE THREAD

**Issue by iiAlanii** [Androz2091/discord-music-bot#31]
After installing all the dependencies, and run node .
It logs the bot in, and stays on "Generating docs...".
I am using the latest version on npm, NodeJS version 16.x.x and DiscordJS version 13.1.x

What is causing the freezing of the bot?

**Comment by timof121** [comment]
did u solve it

**Comment by godsyn** [comment]
I too have this issue with the "current" ( a7cd8eb ) pull.

**Comment by iiAlanii** [comment]
> did u solve it

I did. I still shows "Generating Docs..." but the slash commands work fine.
