### ISSUE TITLE
Age restricted videos

### ISSUE THREAD

**Issue by pateckii** [Androz2091/discord-music-bot#54]
Hello,

Is there any possibility to play age restricted videos?
I tried passing my cookie inside ytdlOptions section but it doesn't help. On youtube webpage even though I am logged in and my age is over 18 yo, youtube player still says that the video might be inappropriate for some users. 
Is there any workaround to get it work?

Errors:
"Error emitted from the queue: Status code: 410" and
"Error emitted from the connection: [PlayerError] Cannot play a resource that has already ended."

**Comment by pateckii** [comment]
Got it working by using play-dl instead of ytdl.

**Comment by clifford64** [comment]
> Got it working by using play-dl instead of ytdl.

Can you please share the information on how to do this? I am very inexperienced with Discord bots, but would like to get age restricted videos working for a private server I have as my friends and I like to try and find the dumbest stuff to play.
